//! Model builder and code generator.

use crate::expr::{Expr, deep_simplify, diff, to_rust};
use std::fmt::Write;

/// A state field definition.
pub struct StateField {
    pub name: String,
    pub dim: usize,
}

/// Builder for constructing estimation models with automatic Jacobian generation.
pub struct ModelBuilder {
    name: String,
    state_fields: Vec<StateField>,
    propagation: Option<Vec<Expr>>,
    propagation_params: Vec<String>,
    observations: Vec<ObservationDef>,
}

struct ObservationDef {
    name: String,
    fields: Vec<StateField>,
    exprs: Vec<Expr>,
    params: Vec<String>,
}

impl ModelBuilder {
    /// Create a new model builder with the given name.
    pub fn new(name: &str) -> Self {
        Self {
            name: name.to_string(),
            state_fields: Vec::new(),
            propagation: None,
            propagation_params: Vec::new(),
            observations: Vec::new(),
        }
    }

    /// Add a state field with given name and dimension.
    /// Returns the starting variable index for this field.
    pub fn state_field(&mut self, name: &str, dim: usize) -> usize {
        let offset = self.state_dim();
        self.state_fields.push(StateField {
            name: name.to_string(),
            dim,
        });
        offset
    }

    /// Total state dimension.
    pub fn state_dim(&self) -> usize {
        self.state_fields.iter().map(|f| f.dim).sum()
    }

    /// Get state variable expressions (one per scalar component).
    pub fn state_vars(&self) -> Vec<Expr> {
        (0..self.state_dim()).map(Expr::var).collect()
    }

    /// Create a named parameter expression.
    pub fn param(&self, name: &str) -> Expr {
        Expr::param(name)
    }

    /// Set the propagation model equations.
    ///
    /// `exprs` must have length == state_dim(). Each expr defines
    /// the next-state value for the corresponding state component.
    ///
    /// `params` lists the parameter names used (e.g., ["dt", "mu"]).
    pub fn set_propagation(&mut self, exprs: Vec<Expr>, params: Vec<&str>) {
        assert_eq!(
            exprs.len(),
            self.state_dim(),
            "Propagation must define {} outputs (state_dim), got {}",
            self.state_dim(),
            exprs.len()
        );
        self.propagation = Some(exprs);
        self.propagation_params = params.iter().map(|s| s.to_string()).collect();
    }

    /// Add an observation model.
    pub fn add_observation(
        &mut self,
        name: &str,
        fields: Vec<(&str, usize)>,
        exprs: Vec<Expr>,
        params: Vec<&str>,
    ) {
        let obs_dim: usize = fields.iter().map(|(_, d)| d).sum();
        assert_eq!(exprs.len(), obs_dim);
        self.observations.push(ObservationDef {
            name: name.to_string(),
            fields: fields
                .into_iter()
                .map(|(n, d)| StateField {
                    name: n.to_string(),
                    dim: d,
                })
                .collect(),
            exprs,
            params: params.iter().map(|s| s.to_string()).collect(),
        });
    }

    /// Generate Rust source code to the given file path.
    pub fn generate(&self, path: &str) {
        let code = self.generate_code();
        std::fs::write(path, code).expect("Failed to write generated code");
    }

    /// Generate Rust source code as a String.
    pub fn generate_code(&self) -> String {
        let mut out = String::new();
        let sdim = self.state_dim();
        let name_lower = self.name.to_lowercase();

        writeln!(out, "// Auto-generated by structured-estimator-codegen. DO NOT EDIT.").unwrap();
        writeln!(out, "#![allow(clippy::all)]").unwrap();
        writeln!(out).unwrap();
        writeln!(out, "use nalgebra::{{SMatrix, SVector}};").unwrap();
        writeln!(out).unwrap();

        // State dimension constant
        writeln!(out, "pub const STATE_DIM: usize = {};", sdim).unwrap();
        writeln!(out).unwrap();

        // State field info (for documentation)
        writeln!(out, "// State layout:").unwrap();
        let mut offset = 0;
        for f in &self.state_fields {
            writeln!(
                out,
                "//   [{:>2}..{:>2}] {} (dim={})",
                offset,
                offset + f.dim,
                f.name,
                f.dim
            )
            .unwrap();
            offset += f.dim;
        }
        writeln!(out).unwrap();

        // Propagation function
        if let Some(ref exprs) = self.propagation {
            let params_sig = self
                .propagation_params
                .iter()
                .map(|p| format!("{}: f64", p))
                .collect::<Vec<_>>()
                .join(", ");
            let params_comma = if params_sig.is_empty() {
                String::new()
            } else {
                format!(", {}", params_sig)
            };

            writeln!(
                out,
                "pub fn {}_propagate(state: &SVector<f64, {}>{}) -> SVector<f64, {}> {{",
                name_lower, sdim, params_comma, sdim
            )
            .unwrap();

            writeln!(out, "    SVector::from([").unwrap();
            for (i, expr) in exprs.iter().enumerate() {
                let comma = if i < exprs.len() - 1 { "," } else { "" };
                writeln!(out, "        {}{}", to_rust(expr), comma).unwrap();
            }
            writeln!(out, "    ])").unwrap();
            writeln!(out, "}}").unwrap();
            writeln!(out).unwrap();

            // Jacobian function (symbolically differentiated)
            writeln!(
                out,
                "pub fn {}_propagate_jacobian(state: &SVector<f64, {}>{}) -> SMatrix<f64, {}, {}> {{",
                name_lower, sdim, params_comma, sdim, sdim
            )
            .unwrap();

            // Compute all partial derivatives
            writeln!(
                out,
                "    #[allow(unused_variables)]"
            )
            .unwrap();
            writeln!(
                out,
                "    let _ = state; // ensure state is used even if all derivs are const"
            )
            .unwrap();

            writeln!(out, "    SMatrix::from_row_slice(&[").unwrap();
            for i in 0..sdim {
                for j in 0..sdim {
                    let d = deep_simplify(&diff(&exprs[i], j));
                    let comma = if i == sdim - 1 && j == sdim - 1 {
                        ""
                    } else {
                        ","
                    };
                    writeln!(out, "        {}{}", to_rust(&d), comma).unwrap();
                }
            }
            writeln!(out, "    ])").unwrap();
            writeln!(out, "}}").unwrap();
            writeln!(out).unwrap();
        }

        // Observation functions
        for obs in &self.observations {
            let obs_lower = obs.name.to_lowercase();
            let odim: usize = obs.fields.iter().map(|f| f.dim).sum();

            let params_sig = obs
                .params
                .iter()
                .map(|p| format!("{}: f64", p))
                .collect::<Vec<_>>()
                .join(", ");
            let params_comma = if params_sig.is_empty() {
                String::new()
            } else {
                format!(", {}", params_sig)
            };

            // Forward function
            writeln!(
                out,
                "pub fn {}_predict(state: &SVector<f64, {}>{}) -> SVector<f64, {}> {{",
                obs_lower, sdim, params_comma, odim
            )
            .unwrap();
            writeln!(out, "    SVector::from([").unwrap();
            for (i, expr) in obs.exprs.iter().enumerate() {
                let comma = if i < obs.exprs.len() - 1 { "," } else { "" };
                writeln!(out, "        {}{}", to_rust(expr), comma).unwrap();
            }
            writeln!(out, "    ])").unwrap();
            writeln!(out, "}}").unwrap();
            writeln!(out).unwrap();

            // Observation Jacobian
            writeln!(
                out,
                "pub fn {}_jacobian(state: &SVector<f64, {}>{}) -> SMatrix<f64, {}, {}> {{",
                obs_lower, sdim, params_comma, odim, sdim
            )
            .unwrap();
            writeln!(out, "    #[allow(unused_variables)]").unwrap();
            writeln!(out, "    let _ = state;").unwrap();
            writeln!(out, "    SMatrix::from_row_slice(&[").unwrap();
            for i in 0..odim {
                for j in 0..sdim {
                    let d = deep_simplify(&diff(&obs.exprs[i], j));
                    let comma = if i == odim - 1 && j == sdim - 1 {
                        ""
                    } else {
                        ","
                    };
                    writeln!(out, "        {}{}", to_rust(&d), comma).unwrap();
                }
            }
            writeln!(out, "    ])").unwrap();
            writeln!(out, "}}").unwrap();
            writeln!(out).unwrap();
        }

        out
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_linear_model_codegen() {
        let mut m = ModelBuilder::new("Linear");
        let _pos_start = m.state_field("position", 3);
        let _vel_start = m.state_field("velocity", 3);

        let s = m.state_vars();
        let dt = m.param("dt");

        m.set_propagation(
            vec![
                s[0].clone() + s[3].clone() * dt.clone(),
                s[1].clone() + s[4].clone() * dt.clone(),
                s[2].clone() + s[5].clone() * dt.clone(),
                s[3].clone(),
                s[4].clone(),
                s[5].clone(),
            ],
            vec!["dt"],
        );

        let code = m.generate_code();
        assert!(code.contains("linear_propagate"));
        assert!(code.contains("linear_propagate_jacobian"));
        // The Jacobian should contain "dt" for the off-diagonal blocks
        assert!(code.contains("dt"));
        // And "1.0" for the diagonal
        assert!(code.contains("1.0"));
        // And "0.0" for zero blocks
        assert!(code.contains("0.0"));

        println!("{}", code);
    }

    #[test]
    fn test_with_observation() {
        let mut m = ModelBuilder::new("WithObs");
        m.state_field("position", 3);
        m.state_field("velocity", 3);

        let s = m.state_vars();
        let dt = m.param("dt");

        m.set_propagation(
            vec![
                s[0].clone() + s[3].clone() * dt.clone(),
                s[1].clone() + s[4].clone() * dt.clone(),
                s[2].clone() + s[5].clone() * dt,
                s[3].clone(),
                s[4].clone(),
                s[5].clone(),
            ],
            vec!["dt"],
        );

        // Observation: just position
        m.add_observation(
            "Position",
            vec![("position", 3)],
            vec![s[0].clone(), s[1].clone(), s[2].clone()],
            vec![],
        );

        let code = m.generate_code();
        assert!(code.contains("position_predict"));
        assert!(code.contains("position_jacobian"));

        println!("{}", code);
    }
}
