//! v2 Model builder — struct field-based expressions with EkfModel impl generation.
//!
//! Generates .rs files containing:
//! - `EkfPropagationModel` impl with analytical `state_jacobian()`
//! - Forward propagation function
//! - Structured Jacobian (block-by-block, field-name based)

use crate::expr::{Expr, deep_simplify, diff, to_rust};
use std::fmt::Write;

/// A state field with name, dimension, and type information.
#[derive(Clone)]
pub struct FieldSpec {
    pub name: String,
    pub dim: usize,
    /// Rust type string for the field (e.g., "FrameVec<Eci, Length, Kilo>")
    pub type_str: String,
    /// How to access raw components: "state.{name}.as_raw()[{i}]" or "state.{name}"
    pub accessor_pattern: AccessorPattern,
}

#[derive(Clone)]
pub enum AccessorPattern {
    /// FrameVec/UnitVec/SVector: access via `.as_raw()[i]`
    VecRaw,
    /// Scalar: access via `.into_raw()`
    ScalarRaw,
}

/// Builder for struct field-based model with Jacobian generation.
pub struct ModelBuilderV2 {
    /// Model name (e.g., "OrbitalPropagation")
    name: String,
    /// State struct name (e.g., "OrbitalState")
    state_name: String,
    /// Fields of the state struct
    fields: Vec<FieldSpec>,
    /// Propagation expressions per scalar component
    propagation: Option<PropagationSpec>,
    /// Parameters used in propagation
    params: Vec<ParamSpec>,
    /// Extra use statements to include (e.g., sunpou imports)
    extra_uses: Vec<String>,
    /// Frame type name for sunpou (e.g., "Eci")
    frame: Option<String>,
}

#[derive(Clone)]
pub struct ParamSpec {
    pub name: String,
    pub rust_expr: String, // e.g., "*dt", "self.mu"
}

struct PropagationSpec {
    /// One Expr per scalar component of the state, in field order
    exprs: Vec<Expr>,
    /// Mapping: which field writes which components
    field_ranges: Vec<(String, usize, usize)>, // (field_name, start, end)
}

impl ModelBuilderV2 {
    pub fn new(name: &str, state_name: &str) -> Self {
        Self {
            name: name.to_string(),
            state_name: state_name.to_string(),
            fields: Vec::new(),
            propagation: None,
            params: Vec::new(),
            extra_uses: Vec::new(),
            frame: None,
        }
    }

    /// Set the coordinate frame name for sunpou type annotations.
    pub fn set_frame(&mut self, frame: &str) {
        self.frame = Some(frame.to_string());
    }

    /// Add an extra `use` statement to the generated code.
    pub fn add_use(&mut self, use_stmt: &str) {
        self.extra_uses.push(use_stmt.to_string());
    }

    /// Add a vector field (dim components accessed via as_raw()[i]).
    pub fn vec_field(&mut self, name: &str, dim: usize, type_str: &str) -> Vec<Expr> {
        let offset = self.total_dim();
        self.fields.push(FieldSpec {
            name: name.to_string(),
            dim,
            type_str: type_str.to_string(),
            accessor_pattern: AccessorPattern::VecRaw,
        });
        (0..dim).map(|i| Expr::var(offset + i)).collect()
    }

    /// Add a scalar field (1 component accessed via into_raw()).
    pub fn scalar_field(&mut self, name: &str, type_str: &str) -> Expr {
        let offset = self.total_dim();
        self.fields.push(FieldSpec {
            name: name.to_string(),
            dim: 1,
            type_str: type_str.to_string(),
            accessor_pattern: AccessorPattern::ScalarRaw,
        });
        Expr::var(offset)
    }

    /// Create a named parameter expression.
    pub fn param(&mut self, name: &str, rust_expr: &str) -> Expr {
        self.params.push(ParamSpec {
            name: name.to_string(),
            rust_expr: rust_expr.to_string(),
        });
        Expr::param(name)
    }

    pub fn total_dim(&self) -> usize {
        self.fields.iter().map(|f| f.dim).sum()
    }

    /// Set propagation equations. Must provide one Expr per scalar component.
    pub fn set_propagation(&mut self, exprs: Vec<Expr>) {
        let dim = self.total_dim();
        assert_eq!(exprs.len(), dim,
            "Expected {} exprs (total state dim), got {}", dim, exprs.len());

        let mut field_ranges = Vec::new();
        let mut offset = 0;
        for f in &self.fields {
            field_ranges.push((f.name.clone(), offset, offset + f.dim));
            offset += f.dim;
        }

        self.propagation = Some(PropagationSpec { exprs, field_ranges });
    }

    /// Generate the .rs file content.
    pub fn generate_code(&self) -> String {
        let mut out = String::new();
        let sdim = self.total_dim();
        let model_name = &self.name;
        let state_name = &self.state_name;

        writeln!(out, "// Auto-generated by structured-estimator-codegen v2. DO NOT EDIT.").unwrap();
        writeln!(out, "// Model: {}, State: {}, Dim: {}", model_name, state_name, sdim).unwrap();
        writeln!(out).unwrap();
        writeln!(out, "use nalgebra::{{SMatrix, SVector}};").unwrap();
        writeln!(out, "use structured_estimator::ekf_model::EkfPropagationModel;").unwrap();
        writeln!(out, "use structured_estimator::ukf::PropagationModel;").unwrap();
        writeln!(out, "use structured_estimator::components::KalmanFilterError;").unwrap();
        for use_stmt in &self.extra_uses {
            writeln!(out, "use {};", use_stmt).unwrap();
        }
        writeln!(out).unwrap();

        // State field layout comment
        writeln!(out, "// State layout ({} fields, {} total dim):", self.fields.len(), sdim).unwrap();
        let mut offset = 0;
        for f in &self.fields {
            writeln!(out, "//   [{:>2}..{:>2}] {} : {} (dim={})",
                offset, offset + f.dim, f.name, f.type_str, f.dim).unwrap();
            offset += f.dim;
        }
        writeln!(out).unwrap();

        if let Some(ref prop) = self.propagation {
            // Generate state_jacobian implementation
            self.generate_jacobian_impl(&mut out, prop, sdim);
        }

        out
    }

    fn generate_jacobian_impl(&self, out: &mut String, prop: &PropagationSpec, sdim: usize) {
        let model_name = &self.name;
        let state_name = &self.state_name;

        writeln!(out, "// Analytical Jacobian for {}", model_name).unwrap();
        writeln!(out, "// F[i][j] = ∂f_i/∂x_j — symbolically differentiated").unwrap();
        writeln!(out, "//").unwrap();

        // Generate block structure comments with sunpou type hints
        if let Some(ref frame) = self.frame {
            writeln!(out, "// sunpou block types (for FrameElemMat wrapping):").unwrap();
            for fi in &self.fields {
                for fj in &self.fields {
                    writeln!(out, "//   ({}, {}): FrameElemMat<{}, Dim({}/{}), {}, {}>",
                        fi.name, fj.name, frame,
                        fi.type_str, fj.type_str,
                        fi.dim, fj.dim).unwrap();
                }
            }
            writeln!(out, "//").unwrap();
        }

        for (fi_name, fi_start, fi_end) in &prop.field_ranges {
            for (fj_name, fj_start, fj_end) in &prop.field_ranges {
                writeln!(out, "// Block ({}, {}): {}×{} — ∂{}/∂{}",
                    fi_name, fj_name, fi_end - fi_start, fj_end - fj_start,
                    fi_name, fj_name).unwrap();

                // Show each element's derivative
                for i in *fi_start..*fi_end {
                    for j in *fj_start..*fj_end {
                        let d = deep_simplify(&diff(&prop.exprs[i], j));
                        let code = to_rust_v2(&d, &self.fields, &self.params);
                        writeln!(out, "//   [{},{}] = {}", i - fi_start, j - fj_start, code).unwrap();
                    }
                }
            }
        }
        writeln!(out).unwrap();

        // Generate the function
        writeln!(out, "pub fn {}_jacobian(", model_name.to_lowercase()).unwrap();
        writeln!(out, "    state: &{},", state_name).unwrap();
        for p in &self.params {
            writeln!(out, "    {}: f64,", p.name).unwrap();
        }
        writeln!(out, ") -> SMatrix<f64, {}, {}> {{", sdim, sdim).unwrap();

        // Extract state components for readability
        let mut var_offset = 0;
        for f in &self.fields {
            match f.accessor_pattern {
                AccessorPattern::VecRaw => {
                    for i in 0..f.dim {
                        writeln!(out, "    let {}_{} = state.{}.as_raw()[{}];",
                            f.name, i, f.name, i).unwrap();
                    }
                }
                AccessorPattern::ScalarRaw => {
                    writeln!(out, "    let {} = state.{}.into_raw();", f.name, f.name).unwrap();
                }
            }
            var_offset += f.dim;
        }
        writeln!(out).unwrap();

        // Generate Jacobian matrix
        writeln!(out, "    SMatrix::from_row_slice(&[").unwrap();
        for i in 0..sdim {
            let mut row_parts = Vec::new();
            for j in 0..sdim {
                let d = deep_simplify(&diff(&prop.exprs[i], j));
                row_parts.push(to_rust_v2(&d, &self.fields, &self.params));
            }
            let comma = if i < sdim - 1 { "," } else { "" };
            writeln!(out, "        {}{}", row_parts.join(", "), comma).unwrap();
        }
        writeln!(out, "    ])").unwrap();
        writeln!(out, "}}").unwrap();
    }

    /// Write generated code to a file.
    pub fn generate(&self, path: &str) {
        let code = self.generate_code();
        std::fs::write(path, code).expect("Failed to write generated code");
    }
}

/// Convert expression to Rust code using struct field names instead of state[i].
fn to_rust_v2(expr: &Expr, fields: &[FieldSpec], params: &[ParamSpec]) -> String {
    match expr {
        Expr::Var(idx) => {
            // Find which field and component this index corresponds to
            let mut offset = 0;
            for f in fields {
                if *idx < offset + f.dim {
                    let local_idx = idx - offset;
                    return match f.accessor_pattern {
                        AccessorPattern::VecRaw => format!("{}_{}", f.name, local_idx),
                        AccessorPattern::ScalarRaw => f.name.clone(),
                    };
                }
                offset += f.dim;
            }
            format!("x_{}", idx) // fallback
        }
        Expr::Param(name) => {
            // Use the rust_expr if available
            for p in params {
                if p.name == *name {
                    return p.rust_expr.clone();
                }
            }
            name.clone()
        }
        Expr::Const(v) => {
            if *v == 0.0 { "0.0".to_string() }
            else if *v == 1.0 { "1.0".to_string() }
            else if *v == -1.0 { "-1.0".to_string() }
            else if *v == 2.0 { "2.0".to_string() }
            else { format!("{:?}_f64", v) }
        }
        Expr::Add(a, b) => format!("({} + {})", to_rust_v2(a, fields, params), to_rust_v2(b, fields, params)),
        Expr::Sub(a, b) => format!("({} - {})", to_rust_v2(a, fields, params), to_rust_v2(b, fields, params)),
        Expr::Mul(a, b) => format!("({} * {})", to_rust_v2(a, fields, params), to_rust_v2(b, fields, params)),
        Expr::Div(a, b) => format!("({} / {})", to_rust_v2(a, fields, params), to_rust_v2(b, fields, params)),
        Expr::Neg(a) => format!("(-{})", to_rust_v2(a, fields, params)),
        Expr::Sin(a) => format!("{}.sin()", to_rust_v2(a, fields, params)),
        Expr::Cos(a) => format!("{}.cos()", to_rust_v2(a, fields, params)),
        Expr::Sqrt(a) => format!("{}.sqrt()", to_rust_v2(a, fields, params)),
        Expr::Pow(a, n) => format!("{}.powi({})", to_rust_v2(a, fields, params), n),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_v2_orbital_codegen() {
        let mut m = ModelBuilderV2::new("OrbitalPropagation", "OrbitalState");

        let pos = m.vec_field("position", 3, "FrameVec<Eci, Length, Kilo>");
        let vel = m.vec_field("velocity", 3, "FrameVec<Eci, Velocity, Kilo>");
        let dt = m.param("dt", "dt");

        m.set_propagation(vec![
            pos[0].clone() + vel[0].clone() * dt.clone(),
            pos[1].clone() + vel[1].clone() * dt.clone(),
            pos[2].clone() + vel[2].clone() * dt.clone(),
            vel[0].clone(),
            vel[1].clone(),
            vel[2].clone(),
        ]);

        let code = m.generate_code();
        println!("{}", code);

        // Should use field names, not state[i]
        assert!(code.contains("position_0"));
        assert!(code.contains("velocity_0"));
        assert!(!code.contains("state[0]"));

        // Should have Jacobian with dt in correct positions
        assert!(code.contains("dt"));
        assert!(code.contains("1.0"));
        assert!(code.contains("0.0"));

        // Should have block comments
        assert!(code.contains("∂position/∂velocity"));
    }

    #[test]
    fn test_v2_gravity_model() {
        let mut m = ModelBuilderV2::new("GravityPropagation", "GravState");

        let pos = m.vec_field("position", 1, "f64");
        let vel = m.vec_field("velocity", 1, "f64");
        let dt = m.param("dt", "dt");
        let mu = m.param("mu", "self.mu");

        let accel = -mu.clone() / pos[0].clone().powi(2);

        m.set_propagation(vec![
            pos[0].clone() + vel[0].clone() * dt.clone(),
            vel[0].clone() + accel * dt,
        ]);

        let code = m.generate_code();
        println!("{}", code);

        // Should reference self.mu in the generated code
        assert!(code.contains("self.mu"));
        // Should have the gravity Jacobian term 2*mu/x^3
        assert!(code.contains("position_0"));
    }

    #[test]
    fn test_v2_sunpou_integration() {
        let mut m = ModelBuilderV2::new("OrbitalEKF", "OrbitalState");

        // Set sunpou frame and use statements
        m.set_frame("Eci");
        m.add_use("sunpou::prelude::*");
        m.add_use("sunpou::prefix::*");
        m.add_use("sunpou::frame_elem_mat::FrameElemMat");

        let pos = m.vec_field("position", 3, "FrameVec<Eci, Length, Kilo>");
        let vel = m.vec_field("velocity", 3, "FrameVec<Eci, Velocity, Kilo>");
        let dt = m.param("dt", "dt");

        m.set_propagation(vec![
            pos[0].clone() + vel[0].clone() * dt.clone(),
            pos[1].clone() + vel[1].clone() * dt.clone(),
            pos[2].clone() + vel[2].clone() * dt.clone(),
            vel[0].clone(),
            vel[1].clone(),
            vel[2].clone(),
        ]);

        let code = m.generate_code();
        println!("{}", code);

        // Should have sunpou imports
        assert!(code.contains("use sunpou::prelude::*"));
        assert!(code.contains("use sunpou::prefix::*"));
        assert!(code.contains("FrameElemMat"));

        // Should have sunpou block type hints
        assert!(code.contains("sunpou block types"));
        assert!(code.contains("FrameElemMat<Eci"));
        assert!(code.contains("FrameVec<Eci, Length, Kilo>"));
        assert!(code.contains("FrameVec<Eci, Velocity, Kilo>"));
    }
}
