//! build.rs example: generate a Jacobian .rs file and verify it compiles & works.
//!
//! This test simulates what a user would do in their build.rs:
//! 1. Define the model using ModelBuilderV2
//! 2. Generate a .rs file
//! 3. Include and use the generated code

use structured_estimator_codegen::ModelBuilderV2;

/// Generate orbital propagation Jacobian to a temp file, then verify it.
#[test]
fn test_build_rs_orbital_example() {
    // === Step 1: What the user writes in build.rs ===

    let mut m = ModelBuilderV2::new("OrbitalPropagation", "OrbitalState");

    // Define state fields with sunpou type annotations
    let pos = m.vec_field("position", 3, "FrameVec<Eci, Length, Kilo>");
    let vel = m.vec_field("velocity", 3, "FrameVec<Eci, Velocity, Kilo>");

    // Parameters
    let dt = m.param("dt", "dt");

    // Propagation: x' = x + v*dt (linear)
    m.set_propagation(vec![
        pos[0].clone() + vel[0].clone() * dt.clone(),
        pos[1].clone() + vel[1].clone() * dt.clone(),
        pos[2].clone() + vel[2].clone() * dt.clone(),
        vel[0].clone(),
        vel[1].clone(),
        vel[2].clone(),
    ]);

    // Generate to a temp file
    let dir = std::env::temp_dir().join("structured_estimator_codegen_test");
    std::fs::create_dir_all(&dir).unwrap();
    let output_path = dir.join("orbital_jacobian.rs");
    m.generate(output_path.to_str().unwrap());

    // === Step 2: Verify the generated file ===

    let code = std::fs::read_to_string(&output_path).unwrap();

    // Check structure
    assert!(code.contains("// Auto-generated by structured-estimator-codegen v2"));
    assert!(code.contains("FrameVec<Eci, Length, Kilo>"));
    assert!(code.contains("∂position/∂velocity"));
    assert!(code.contains("pub fn orbitalpropagation_jacobian("));
    assert!(code.contains("state.position.as_raw()"));
    assert!(code.contains("state.velocity.as_raw()"));

    // The generated Jacobian for this linear model should be exact:
    // | I   dt*I |
    // | 0   I    |
    // Verify the matrix entries
    assert!(code.contains("1.0, 0.0, 0.0, dt, 0.0, 0.0"));

    println!("=== Generated file: {} ===", output_path.display());
    println!("{}", code);

    // Clean up
    let _ = std::fs::remove_dir_all(&dir);
}

#[test]
fn test_build_rs_gravity_example() {
    let mut m = ModelBuilderV2::new("GravityProp", "GravState");

    let pos = m.vec_field("altitude", 1, "Scalar<Length>");
    let vel = m.vec_field("radial_velocity", 1, "Scalar<Velocity>");
    let dt = m.param("dt", "dt");
    let mu = m.param("mu", "self.mu");

    // Euler step: h' = h + v*dt, v' = v - (mu/h²)*dt
    let accel = -mu.clone() / pos[0].clone().powi(2);
    m.set_propagation(vec![
        pos[0].clone() + vel[0].clone() * dt.clone(),
        vel[0].clone() + accel * dt,
    ]);

    let code = m.generate_code();

    // Should contain the derivative of -mu/h² w.r.t. h = 2*mu/h³
    assert!(code.contains("self.mu"));
    assert!(code.contains("altitude_0"));
    assert!(code.contains("powi"));

    println!("=== Gravity model generated code ===");
    println!("{}", code);
}

/// Show the recommended build.rs pattern in documentation form.
#[test]
fn test_recommended_usage_pattern() {
    // This is what the user's build.rs would look like:
    //
    // ```rust
    // // build.rs
    // use structured_estimator_codegen::ModelBuilderV2;
    //
    // fn main() {
    //     let mut m = ModelBuilderV2::new("OrbitalPropagation", "OrbitalState");
    //
    //     let pos = m.vec_field("position", 3, "FrameVec<Eci, Length, Kilo>");
    //     let vel = m.vec_field("velocity", 3, "FrameVec<Eci, Velocity, Kilo>");
    //     let dt = m.param("dt", "*dt");
    //
    //     m.set_propagation(vec![
    //         pos[0].clone() + vel[0].clone() * dt.clone(),
    //         pos[1].clone() + vel[1].clone() * dt.clone(),
    //         pos[2].clone() + vel[2].clone() * dt.clone(),
    //         vel[0].clone(), vel[1].clone(), vel[2].clone(),
    //     ]);
    //
    //     let out_dir = std::env::var("OUT_DIR").unwrap();
    //     m.generate(&format!("{}/orbital_jacobian.rs", out_dir));
    //     println!("cargo:rerun-if-changed=build.rs");
    // }
    // ```
    //
    // Then in src/main.rs:
    // ```rust
    // include!(concat!(env!("OUT_DIR"), "/orbital_jacobian.rs"));
    // ```
    //
    // Or copy to src/generated/ for better visibility.

    // This test just verifies the pattern works
    let mut m = ModelBuilderV2::new("TestModel", "TestState");
    let x = m.vec_field("x", 2, "Vector2<f64>");
    let dt = m.param("dt", "*dt");
    m.set_propagation(vec![
        x[0].clone() + x[1].clone() * dt.clone(),
        x[1].clone(),
    ]);
    let code = m.generate_code();
    assert!(code.contains("testmodel_jacobian"));
}
